//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;

namespace VirusSpreadLibrary.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.7.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        [Description("With of the Habitat-Grid in Pixel")]
        public int GridMaxX {
            get {
                return ((int)(this["GridMaxX"]));
            }
            set {
                this["GridMaxX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        [Description("High of the Habitat-Grid in Pixcel")]
        public int GridMaxY {
            get {
                return ((int)(this["GridMaxY"]));
            }
            set {
                this["GridMaxY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        [Description("Start poulation for Persons")]
        public long InitialPersonPopulation {
            get {
                return ((long)(this["InitialPersonPopulation"]));
            }
            set {
                this["InitialPersonPopulation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        [Description("Start poulation for Viruses")]
        public long InitialVirusPopulation {
            get {
                return ((long)(this["InitialVirusPopulation"]));
            }
            set {
                this["InitialVirusPopulation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        [Description("Number of iterations for the Simulation")]
        public long maxIterations {
            get {
                return ((long)(this["maxIterations"]));
            }
            set {
                this["maxIterations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        [Description("Internal use - to save actual MainForm size and position")]
        public global::System.Drawing.Point Form_Config_WindowLocation {
            get {
                return ((global::System.Drawing.Point)(this["Form_Config_WindowLocation"]));
            }
            set {
                this["Form_Config_WindowLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2056, 1010")]
        [Description("Internal use - to save actual MainForm size and position")]
        public global::System.Drawing.Size Form_Config_WindowSize {
            get {
                return ((global::System.Drawing.Size)(this["Form_Config_WindowSize"]));
            }
            set {
                this["Form_Config_WindowSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        [Description("Not implemented yet - choose Grid Cell Colors")]
        public string ColorList {
            get {
                return ((string)(this["ColorList"]));
            }
            set {
                this["ColorList"] = value;
            }
        }
    }
}
