//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;

namespace VirusSpreadLibrary.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.7.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        [Description("Width of the Grid Filed - pixel")]
        public int GridMaxX {
            get {
                return ((int)(this["GridMaxX"]));
            }
            set {
                this["GridMaxX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        [Description("Higth of the Grid Filed - pixel")]
        public int GridMaxY {
            get {
                return ((int)(this["GridMaxY"]));
            }
            set {
                this["GridMaxY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        [Description("Start poulation for Persons - long")]
        public long InitialPersonPopulation {
            get {
                return ((long)(this["InitialPersonPopulation"]));
            }
            set {
                this["InitialPersonPopulation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        [Description("Start poulation for Viruses - long")]
        public long InitialVirusPopulation {
            get {
                return ((long)(this["InitialVirusPopulation"]));
            }
            set {
                this["InitialVirusPopulation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        [Description("Number of maximal iterations for the Simulation - long")]
        public long maxIterations {
            get {
                return ((long)(this["maxIterations"]));
            }
            set {
                this["maxIterations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        [Description("Internal use - to save actual MainForm size and position")]
        public global::System.Drawing.Point Form_Config_WindowLocation {
            get {
                return ((global::System.Drawing.Point)(this["Form_Config_WindowLocation"]));
            }
            set {
                this["Form_Config_WindowLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2056, 1010")]
        [Description("Internal use - to save actual MainForm size and position")]
        public global::System.Drawing.Size Form_Config_WindowSize {
            get {
                return ((global::System.Drawing.Size)(this["Form_Config_WindowSize"]));
            }
            set {
                this["Form_Config_WindowSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        [Description("Not implemented yet - choose Grid Cell Colors")]
        public string ColorList {
            get {
                return ((string)(this["ColorList"]));
            }
            set {
                this["ColorList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        [Description("allow virus global moovment - true : movement within the distance limit only from the home coordinate. false: movement within the distance limit from the new current coordinate, therefore over the entire grid field possible")]
        public bool VirusMoveGlobal {
            get {
                return ((bool)(this["VirusMoveGlobal"]));
            }
            set {
                this["VirusMoveGlobal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        [Description("allow person global moovment - true : movement within the distance limit only from the home coordinate. false: movement within the distance limit from the new current coordinate, therefore over the entire grid field possible")]
        public bool PersonMoveGlobal {
            get {
                return ((bool)(this["PersonMoveGlobal"]));
            }
            set {
                this["PersonMoveGlobal"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        [Description("Timer in milli seconds : standard 1 ms - bigger values slows down the iterations and the redraw of grid field form")]
        public int GridFormTimer
        {
            get
            {
                return ((int)(this["GridFormTimer"]));
            }
            set
            {
                this["GridFormTimer"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        [Description("default false: If true allows movement tracking over the whole time - all iterations, as the person or virus at the old grid coordinate are not deleted after movment")]

        public bool TrackMovment
        {
            get
            {
                return ((bool)(this["TrackMovment"]));
            }
            set
            {
                this["TrackMovment"] = value;
            }
        }
    }
}
